# Getting Started

This notebook verifies your environment is set up correctly and shows how to access course data. 

All course data lives in a single file, pointed to by the link you see below. The cell below downloads that file and attaches it for usage with duckdb, it might take up to a minute (depending on your internet speed).

**If this notebook runs successfully, your setup is complete. If it does not (you see errors when running cells), please let me know ASAP.**

In [ ]:
import duckdb
import gzip
import urllib.request
from pathlib import Path

data_url = "https://pub-c88b3a7f2ed141418355b2bfb03c96e6.r2.dev/data.duckdb.gz"
db_path = "data.duckdb"

request = urllib.request.Request(data_url, headers={"User-Agent": "Mozilla/5.0"})
with urllib.request.urlopen(request) as response:
    with gzip.open(response, "rb") as gz:
        with open(db_path, "wb") as f:
            f.write(gz.read())

conn = duckdb.connect()
conn.execute(f"ATTACH '{db_path}' AS data (READ_ONLY)")

In [ ]:
conn.execute("SHOW TABLES FROM data.attendance").df()

         name
0  attendance
1      school
2     subject

In [7]:
conn.execute("SELECT * FROM data.attendance.attendance LIMIT 10").df()

,unique_id,report_period,school_code,division_code,student_class,subject_code,electronic_diary,student_count_nsa,student_count_diary,excused_lessons_illness,excused_lessons_other,unexcused_lessons
0,000000651dac71b,2018-11-01,190205760,None,5,7101,NASC,6,5,2,0,0
1,00000805bb45ccd,2022-06-01,191317794,None,9,5301,NASC,13,13,6,2,0
2,000009a7a440493,2024-09-01,190007344,None,8,7104,NASC,50,52,16,1,0
3,00000a06785e2a6,2024-04-01,302523034,None,2,9101,Tamo,126,45,19,0,0
4,00000d7bce7525c,2023-12-01,302420721,None,10,9101,Tamo,133,133,24,1,14
5,00000e75d45273e,2025-12-01,305913274,None,10,14004,Tamo,29,28,8,7,0
6,000011a61b5031d,2023-02-01,303378556,None,9,9101,Tamo,21,21,1,0,6
7,00001429ad87a18,2017-11-01,195095992,None,10,20001,NASC,52,51,21,10,0
8,000014408f81ae5,2023-06-01,190985253,None,4,3001,NASC,5,5,0,0,0
9,000014f299fa5d2,2019-03-01,191318896,None,10,11101,Tamo,10,10,2,0,7